name: Python CI

on:
  push:
    branches:
      - main
      - task-1
      - task-2
      - task-3
      - task-4

pull_request:
  branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flake8
      run: |
        flake8 src

    - name: Run tests
      run: |
        pytest